# Generated by Django 3.2.18 on 2023-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='submitted',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
