# Generated by Django 3.2.18 on 2023-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230419_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='submitted',
            field=models.IntegerField(default=0),
        ),
    ]
